version: '3.3'

services:
  janus:
    image: tokend/janus:latest
    restart: unless-stopped
    volumes:
      - ./configs/janus.toml:/etc/janus/janus.toml
  core:
    depends_on:
      - janus
    image: tokend/core:3.0.0
    restart: unless-stopped
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=core
      - POSTGRES_DB=core
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - ./configs/core.ini:/config.ini
      - core-data:/data
  horizon:
    depends_on:
      - core
    image: tokend/horizon:3.0.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=horizon
      - POSTGRES_PASSWORD=horizon
      - POSTGRES_DB=horizon
      - PGDATA=/pgdata
    volumes:
      - ./configs/horizon.yaml:/config.yaml
  api:
    image: tokend/identity:3.0.0
    restart: unless-stopped
    depends_on:
      - horizon
      - api_db
    environment: 
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/api.yml:/config.yaml
    command: run
  api_db:
    restart: unless-stopped
    image: tokend/postgres-ubuntu:9.6
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=api
      - PGDATA=/pgdata
    volumes:
      - api-data:/pgdata
  upstream:
    restart: unless-stopped
    image: nginx
    volumes:
    - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8000:80"
  initscripts:
    depends_on:
      - horizon
    image: tokend/terraform-provider-tokend:latest
    restart: on-failure
    volumes:
      - ./terraform:/opt/config
      - terraform-data:/opt/state
    entrypoint: ""
    command: /opt/config/apply.sh
  web_client:
    restart: unless-stopped    
    image: tokend/web-client:1.3.0
    volumes:
      - ./configs/client.js:/usr/share/nginx/html/static/env.js
    ports:
      - 8060:80
  admin_client:
    restart: unless-stopped
    image: tokend/admin-client:1.3.0
    volumes:
      - ./configs/client.js:/usr/share/nginx/html/static/env.js
    ports:
      - 8070:80
  storage:
    image: minio/minio:RELEASE.2019-01-31T00-31-19Z
    restart: unless-stopped
    environment:
      - MINIO_ACCESS_KEY=miniominio
      - MINIO_SECRET_KEY=sekritsekrit
    volumes:
      - storage-data:/data
    command: server /data
  adks:
    image: tokend/adks:1.0.0
    restart: unless-stopped
    depends_on:
      - horizon
      - adks_db
    ports:
      - 8006:80
    volumes:
      - ./configs/adks.toml:/config.toml
  adks_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=adks
      - POSTGRES_PASSWORD=adks
      - POSTGRES_DB=adks
      - PGDATA=/pgdata
    volumes:
      - adks-data:/pgdata

volumes:
  adks-data:
  api-data:
  core-data:
  horizon-data:
  storage-data:
  terraform-data:
