version: '3.3'

services:
  janus:
    image: tokend/janus:latest
    restart: unless-stopped
    volumes:
      - ./configs/janus.toml:/etc/janus/janus.toml
  upstream:
    image: nginx
    restart: unless-stopped
    volumes:
    - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8000:80"
  salecloser:
    image: tokend/sale-closer-svc:1.0.0
    depends_on:
      - horizon
    restart: unless-stopped
    volumes:
      - ./configs/salecloser.yaml:/config.yaml
    environment:
      - KV_VIPER_FILE=/config.yaml
    command: "run"
  adks:
    image: tokend/adks:1.0.0
    restart: unless-stopped
    depends_on:
      - horizon
      - adks_db
    ports:
      - 8006:80
    volumes:
      - ./configs/adks.toml:/config.toml
  adks_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=adks
      - POSTGRES_PASSWORD=adks
      - POSTGRES_DB=adks
      - PGDATA=/pgdata
    volumes:
      - adks-data:/pgdata
  core:
    image: tokend/core:3.1.0-rc.1
    depends_on:
      - janus
    restart: unless-stopped
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=core
      - POSTGRES_DB=core
      - PGDATA=/data/pgdata
      - ENSUREDB=1
      - CONFIG=/core-config.ini
    volumes:
      - ./configs/core.ini:/core-config.ini
      - core-data:/data
  horizon:
    image: tokend/horizon:3.1.0-rc.0
    depends_on:
      - core
    restart: unless-stopped
    environment:
      - POSTGRES_USER=horizon
      - POSTGRES_PASSWORD=horizon
      - POSTGRES_DB=horizon
      - PGDATA=/pgdata
    volumes:
      - ./configs/horizon.yaml:/config.yaml
  api:
    image: tokend/identity:4.0.0-rc.0
    restart: unless-stopped
    depends_on:
      - horizon
      - api_db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/api.yml:/config.yaml
    command: run
  api_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=api
      - PGDATA=/pgdata
    volumes:
      - api-data:/pgdata
  initscripts:
    image: tokend/terraform-provider-tokend:0.2.0
    depends_on:
      - horizon
    restart: on-failure
    volumes:
      - ./terraform:/opt/config
      - terraform-data:/opt/state
    entrypoint: ""
    command: /opt/config/apply.sh
  web_client:
    image: tokend/web-client:1.4.0-rc.1
    restart: unless-stopped
    volumes:
      - ./configs/client.js:/usr/share/nginx/html/static/env.js
    ports:
      - 8060:80
  admin_client:
    image: tokend/admin-client:1.4.0-rc.0
    restart: unless-stopped
    volumes:
      - ./configs/client.js:/usr/share/nginx/html/static/env.js
    ports:
      - 8070:80
  storage:
    image: minio/minio:RELEASE.2019-01-31T00-31-19Z
    restart: unless-stopped
    environment:
      - MINIO_ACCESS_KEY=miniominio
      - MINIO_SECRET_KEY=sekritsekrit
      - MINIO_BROWSER=off
    volumes:
      - storage-data:/data
    command: server /data

  ##
  ## Auxiliary modules
  ##

  charts:
    image: tokend/charts:0.2.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/charts.yaml:/config.yaml
    command: run

  ##
  ## Integration services
  ##

  ## Coinpayments

  coinpayments-deposit:
    image: tokend/coinpayments:0.2.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-deposit.yaml:/config.yaml
    command: deposit
  coinpayments-deposit-verify:
    image: tokend/coinpayments:0.2.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-deposit-verify.yaml:/config.yaml
    command: deposit-verify
  coinpayments-withdraw:
    image: tokend/coinpayments:0.2.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/coinpayments-withdraw.yaml:/config.yaml
    command: withdraw

volumes:
  adks-data:
  api-data:
  core-data:
  horizon-data:
  storage-data:
  terraform-data:
