api:
  horizon_url: http://horizon
  account_manager: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4
  skip_signature_check: true

db:
  url: postgres://api:api@api_db/api?sslmode=disable
  max_idle: 4
  max_connections: 12

horizon:
  url: http://horizon
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4

notificator:
  disabled: true

salesforce:
  disabled: true

listener:
  addr: :80

log:
  level: info
  slow_query_bound: 300ms
  slow_request_bound: 1s

sentry:
  dsn: https://e48aaa3c7f764c0ebe04dba3a2bb6eb8:ba2a1c169ff54e06b09b32ace9cdf92b@sentry.tokend.services/15
  level: warn

aws:
  credentials: "static"
  endpoint: storage:9000
  disable_ssl: true
  access_key: "miniominio"
  secret_key: "sekritsekrit"
  region: "us-east-1"

storage:
  backend: "aws"
  bucket: "api"
  ensure_bucket: true
  client_url: http://localhost:8000/_/storage/
  media_types:
    general:
      - application/pdf
      - image/jpeg
      - image/png
      - image/gif

wallets:
  disable_confirm: true

tx_watcher:
  disabled: false

janus:
  endpoint: http://janus:8000
  upstream: http://api
  surname:  api